import React from 'react';

import { Montserrat } from 'next/font/google';
import 'react-toastify/dist/ReactToastify.css';

// import { ReduxWraper } from 'elo/front/react/Redux';

import './global.css';
import { ToastContainer } from 'react-toastify';

// const robotoCondensed = Roboto_Condensed({ subsets: ['latin'], weight: '400' });
const montserratFont = Montserrat({ subsets: ['latin'], weight: '400' });

export const metadata = {
  title: 'Welcome to elo-next',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${montserratFont.className} antialised`}
        style={{
          backgroundImage: `url('/backgrounds/background-1.jpeg')`,
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat',
          height: '100vh',
        }}
      >
        {/* TODO: Move to App */}
        <ToastContainer />

        <div id="body-wraper">
          <React.StrictMode>{children}</React.StrictMode>
        </div>
      </body>
    </html>
  );
}
